# Generated by Django 4.1.4 on 2022-12-13 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 12, 13, 11, 7, 43, 646779, tzinfo=datetime.timezone.utc)),
        ),
    ]
